### ISSUE TITLE
Error with permissions on uwsgi.sock

### ISSUE THREAD

**Issue by dezoito** [vfxGer/alternative_nginx_uwsgi_flask_docker#1]
Greetings,

After cloning your repo, I ran `docker-compose build `and `docker-compose up` with no issues.

However, when trying to run the Hello world app from the browser, I get the error below:

`server_1  | 2017/06/19 22:01:56 [crit] 7#7: *1 connect() to unix:///sockets/uwsgi.sock failed (13: Permission denied) while connecting to upstream, client: 172.24.0.1, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///sockets/uwsgi.sock:", host: "127.0.0.1:3000"`

Docker runs under it's own account in the host machine (not root), so I thought that might have been the cause, but the error persists even when I ran it as root.

I've done my homework trying to fix this, but nothing helped so far... any suggestions?

**Comment by vfxGer** [comment]
Try opening up the permissions on the socket object in ./sockets i.e. do a chmod 777 *
It's a bit of a bad solution but it works.

**Comment by dezoito** [comment]
Thank you for the quick reply!

What would be the best way to automate that? 

Add a `RUN chmod 777 *` to the end of the Dockerfile?

**Comment by vfxGer** [comment]
You'll only need to do it once because the socket object is persistent. 
Generally people say to avoid this socket way of doing it. 
I am not getting this problem locally at the moment so let me try to reproduce.

**Comment by vfxGer** [comment]
Ok simple fix in the end just needed to change the uwsgi file to open the permissions there. There's probably a better more secure solution.

**Comment by dezoito** [comment]
Awesome!

Works perfectly now.
